### ISSUE TITLE
Add the option to disallow translation past image borders in clipper-fixed

### ISSUE THREAD

**Issue by jmikh** [timtnleeProject/vuejs-clipper#59]
You can keep moving the image indefinitely. There should be the option to have the bounding box always intersecting with the image at least.

![ezgif-3-881a08acb623](https://user-images.githubusercontent.com/4601618/79674101-0f58ec80-81ae-11ea-8e0e-2d5ae64ca4e9.gif)

**Comment by timtnleeProject** [comment]
Hi @jmikh ,
It has difficulty setting the image position precisely since it's using `transform`: `scale`, so it's hard to handle image position when it's out of bounding but users still scaling the image.

Also, I think it's too verbose for this component to restrict image inside the bound.
I'm sorry but recently I will not work on this feature.

**Comment by David-Crty** [comment]
I have exactly the same need as described in this issue, 
@jmikh did you find any solution or do you have any starting point for this to work on my project ?
I could do a PR for this
