### ISSUE TITLE
Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported

### ISSUE THREAD

**Issue by wvansl** [timtnleeProject/vuejs-clipper#7]
I get this error when doing canvas.toBlob.
"Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported"

```
const canvas = this.$refs.clipper.clip();
var result = canvas.toDataURL("image/jpg", 1);//canvas->image
```

How do I get the image to allow crossOrigins?
I tried like this but it didnt work:
`this.$refs.clipper.imgEl.crossOrigin="Anonymous";`
The imgElement is set to crossOrigin but the error remains.

Any solution?

**Comment by timtnleeProject** [comment]
You can only clip images that are served in the same origin or from local files unless servers that serve images provide `Access-Control-Allow-Origin` header to allow [CORS](https://developer.mozilla.org/zh-TW/docs/Web/HTTP/CORS). 

Otherwise, the images from other origins can't be edited (like transform to canvas in order to change its pixels).
